#!/usr/bin/env bun

/**
 * agent-loop — Distributed automation daemon
 *
 * Usage:
 *   bun run src/index.ts                    # Start daemon (reads ~/.agent-loop/config.json)
 *   bun run src/index.ts --repo owner/repo  # Start with repo override
 *   bun run src/index.ts --once             # Run one poll cycle then exit
 */

import { parseArgs } from 'node:util'
import { AgentDaemon, DEFAULT_HEALTH_SERVER_PORT, DEFAULT_HEALTH_SERVER_HOST, type HealthServerConfig } from './daemon'
import { loadConfig, type CliArgs } from './config'
import { collectDaemonObservability, formatDoctorReport, formatStatusReport } from './status'

type PartialHealthServerConfig = Partial<HealthServerConfig>

async function main() {
  const { values: args } = parseArgs({
    options: {
      repo: { type: 'string', short: 'r' },
      pat: { type: 'string', short: 'p' },
      concurrency: { type: 'string', short: 'c' },
      'poll-interval': { type: 'string' },
      'machine-id': { type: 'string' },
      'dry-run': { type: 'boolean' },
      'metrics-port': { type: 'string' },
      once: { type: 'boolean' },
      status: { type: 'boolean' },
      doctor: { type: 'boolean' },
      'health-host': { type: 'string' },
      'health-port': { type: 'string' },
      help: { type: 'boolean' },
    },
  })

  const metricsPort = args['metrics-port']
    ? parseInt(args['metrics-port'] as string)
    : undefined

  if (args.help) {
    printHelp()
    process.exit(0)
  }

  if (args.status || args.doctor) {
    let fallbackRepo: string | undefined
    try {
      fallbackRepo = loadConfig({
        repo: args.repo as string | undefined,
        pat: args.pat as string | undefined,
        machineId: args['machine-id'] as string | undefined,
      }).repo
    } catch {
      fallbackRepo = args.repo as string | undefined
    }

    const snapshot = await collectDaemonObservability({
      healthHost: (args['health-host'] as string | undefined) ?? DEFAULT_HEALTH_SERVER_HOST,
      healthPort: args['health-port'] ? parseInt(args['health-port'] as string) : DEFAULT_HEALTH_SERVER_PORT,
      metricsPort,
      includeGitHubAudit: Boolean(args.doctor),
      fallbackRepo,
    })
    console.log(args.doctor ? formatDoctorReport(snapshot) : formatStatusReport(snapshot))
    process.exit(snapshot.ok ? 0 : 1)
  }

  const cliArgs: CliArgs = {
    repo: args.repo as string | undefined,
    pat: args.pat as string | undefined,
    concurrency: args.concurrency ? parseInt(args.concurrency as string) : undefined,
    pollIntervalMs: args['poll-interval'] ? parseInt(args['poll-interval'] as string) : undefined,
    machineId: args['machine-id'] as string | undefined,
    dryRun: args['dry-run'] as boolean | undefined,
    once: args.once as boolean | undefined,
    healthHost: args['health-host'] as string | undefined,
    healthPort: args['health-port'] ? parseInt(args['health-port'] as string) : undefined,
  }

  // Build health server config
  const healthServerConfig: PartialHealthServerConfig = {}
  if (cliArgs.healthHost) healthServerConfig.host = cliArgs.healthHost
  if (cliArgs.healthPort) healthServerConfig.port = cliArgs.healthPort

  try {
    const config = loadConfig(cliArgs)

    const daemon = new AgentDaemon(config, console, healthServerConfig, metricsPort)

    // Graceful shutdown
    const shutdown = async (signal: string) => {
      console.log(`\n[agent-loop] received ${signal}`)
      await daemon.stop()
      process.exit(0)
    }

    process.on('SIGINT', () => shutdown('SIGINT'))
    process.on('SIGTERM', () => shutdown('SIGTERM'))

    await daemon.start()

    if (cliArgs.once) {
      console.log('[agent-loop] --once mode: waiting for first issue to complete...')
      await daemon.waitForInFlightProcess()
      await daemon.stop()
      process.exit(0)
    }

    console.log('[agent-loop] daemon running. Press Ctrl+C to stop.')
  } catch (err) {
    if (err instanceof Error && err.name === 'ConfigError') {
      console.error(`[agent-loop] config error: ${err.message}`)
      console.error('Run with --help for usage information.')
      process.exit(1)
    }
    throw err
  }
}

function printHelp() {
  console.log(`
agent-loop — Distributed automation daemon

Usage:
  agent-loop [options]
  agent-loop --status [--health-port 9310]
  agent-loop --doctor [--health-port 9310]

Options:
  -r, --repo <owner/repo>     Target GitHub repository
  -p, --pat <token>           GitHub Personal Access Token (or set GITHUB_TOKEN / GH_TOKEN / gh auth login)
  -c, --concurrency <n>       Max concurrent agent tasks (default: 1)
      --poll-interval <ms>    Poll interval in milliseconds (default: 60000)
      --machine-id <id>       Override machine ID (auto-generated by default)
      --health-host <host>    Health check server host (default: 127.0.0.1)
      --health-port <port>    Health check server port (default: 9310)
      --metrics-port <port>   Prometheus metrics port (default: 9090)
      --status                Print a compact local daemon status report and exit
      --doctor                Print a detailed local daemon diagnostic report and exit
      --dry-run               Simulate without making changes
      --once                  Run one poll cycle then exit
      --help                  Show this help message

Health Check:
  GET /health                Returns daemon status in JSON format
Metrics:
  Prometheus metrics are exposed at /metrics on the metrics port.
  A /health endpoint is also available for health checks.

Configuration:
  Machine config is read from ~/.agent-loop/config.json
  Project config is optionally read from ./.agent-loop/project.json in the current repo
  Environment variables: GITHUB_TOKEN, GH_TOKEN
  Authentication fallback: if no PAT is configured, agent-loop will try gh auth token

Examples:
  agent-loop --repo octocat/hello-world
  agent-loop --repo owner/repo --concurrency 2
  agent-loop --health-port 8080
  agent-loop --metrics-port 9090
  agent-loop --status
  agent-loop --doctor --health-port 9311 --metrics-port 9091
  GITHUB_TOKEN=ghp_xxx agent-loop --once
`)
}

main().catch((err) => {
  console.error('[agent-loop] fatal error:', err)
  process.exit(1)
})
